services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.5.2
    container_name: stirling-pdf
    expose:
      - 8080
    environment:
      - SECURITY_ENABLELOGIN=false
      - LANGS=en_US
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`${STIRLING_PDF_HOSTNAME?}`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stirling-pdf.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/stirling-pdf/pipeline:/pipeline
      - ${DOCKER_DATA_DIR}/stirling-pdf/configs:/configs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    profiles:
      - stirling-pdf
      - all
    restart: unless-stopped
