include:
  - apps/aiometadata/compose.yaml
  - apps/aiostreams/compose.yaml
  - apps/authelia/compose.yaml
  - apps/beszel/compose.yaml
  - apps/dozzle/compose.yaml
  - apps/honey/compose.yaml
  - apps/init/compose.yaml
  - apps/mediaflow-proxy/compose.yaml
  - apps/stirling-pdf/compose.yaml
  - apps/traefik/compose.yaml
  - apps/uptime-kuma/compose.yaml

networks:
  default:
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
    name: ${DOCKER_NETWORK_NAME:-compose-network}
