services:
  aiostreams:
    image: viren070/aiostreams:v2.22.0
    container_name: aiostreams
    user: "${PUID}:${PGID}"
    expose:
      - 3000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiostreams.rule=Host(`${AIOSTREAMS_HOSTNAME?}`)"
      - "traefik.http.routers.aiostreams.entrypoints=websecure"
      - "traefik.http.routers.aiostreams.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aiostreams.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/aiostreams/data:/app/data
    depends_on:
      aiostreams-postgres:
        condition: service_healthy
    profiles:
      - aiostreams
      - all
    restart: unless-stopped

  aiostreams-postgres:
    image: postgres:18-alpine
    container_name: aiostreams-postgres
    user: "${PUID}:${PGID}"
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ${DOCKER_DATA_DIR}/aiostreams/db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    profiles:
      - aiostreams
      - all
    restart: unless-stopped
